"""Generate data/world.js: compact country outlines for the map picker.

    python tools/build_world.py

The Natural Earth 110m source is 839 KB of GeoJSON with full coordinate precision and
a hundred properties per feature, none of which the map needs. This keeps the rings,
rounds coordinates to two decimals (about a kilometre, far finer than a 110m map
resolves) and drops slivers, which gets it to roughly a quarter of the size.

Output is keyed by ISO3 so it joins directly to the `iso` field in data/regions.js. A
name index is emitted alongside, because merged groups in regions.js list their members
by name -- "Sahel & Horn of Africa" covers Chad, Ethiopia, Mali and Niger -- and the map
has to colour those countries as part of the group.

Coordinates stay as longitude and latitude. Projecting here would bake in the choice;
src/map.js projects at draw time so it can be changed without regenerating.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "geo-cache", "ne_110m_admin_0_countries.geojson")
TINY = os.path.join(HERE, "geo-cache", "ne_110m_admin_0_tiny_countries.geojson")
OUT = os.path.join(HERE, os.pardir, "data", "world.js")

PRECISION = 2
MIN_RING_POINTS = 4
MIN_RING_SPAN = 0.6   # degrees; a ring smaller than this is a sliver at world scale

# Antarctica is dropped. Nobody selects it, it has no profile, and in an equal-area
# projection it occupies roughly a third of the vertical extent -- so removing it makes
# every country anyone might actually click substantially larger.
SKIP = {"ATA"}


def rings_of(geom):
    if geom["type"] == "Polygon":
        return [geom["coordinates"][0]]          # outer ring only; holes are invisible here
    return [poly[0] for poly in geom["coordinates"]]


def clean(ring):
    out, last = [], None
    for x, y in ring:
        p = [round(x, PRECISION), round(y, PRECISION)]
        if p != last:
            out.append(p)
            last = p
    if len(out) < MIN_RING_POINTS:
        return None
    xs = [p[0] for p in out]
    ys = [p[1] for p in out]
    if max(xs) - min(xs) < MIN_RING_SPAN and max(ys) - min(ys) < MIN_RING_SPAN:
        return None
    return out


def main():
    with open(SRC, encoding="utf-8") as fh:
        gj = json.load(fh)

    shapes, names, points = {}, {}, {}
    for f in gj["features"]:
        p = f["properties"]
        iso = p.get("ADM0_A3") or p.get("ISO_A3")
        if not f.get("geometry") or not iso or iso == "-99" or iso in SKIP:
            continue
        kept = [r for r in (clean(r) for r in rings_of(f["geometry"])) if r]
        if not kept:
            continue
        shapes[iso] = kept
        if p.get("NAME"):
            names[p["NAME"]] = iso

    # Micro-states have no polygon at 1:110m -- Maldives, Tuvalu, Barbados, Singapore
    # and the rest simply vanish. They are exactly the places this project's locale
    # feature matters most for, so Natural Earth's companion points layer supplies a
    # coordinate and the map draws them as dots.
    if os.path.exists(TINY):
        with open(TINY, encoding="utf-8") as fh:
            tg = json.load(fh)
        for f in tg["features"]:
            p = f["properties"]
            iso = p.get("ADM0_A3")
            g = f.get("geometry")
            if not iso or iso in shapes or not g or g["type"] != "Point":
                continue
            points[iso] = [round(g["coordinates"][0], PRECISION),
                           round(g["coordinates"][1], PRECISION)]
            if p.get("NAME"):
                names[p["NAME"]] = iso

    body = json.dumps({"shapes": shapes, "names": names, "points": points},
                      separators=(",", ":"), ensure_ascii=False)
    header = ("/* GENERATED by tools/build_world.py -- do not edit by hand.\n"
              " * Natural Earth 1:110m admin-0, public domain. Outer rings only,\n"
              " * coordinates in lon/lat rounded to 2 decimals. Keyed by ISO3 so it\n"
              " * joins to the `iso` field in data/regions.js. */\n")
    with open(OUT, "w", encoding="utf-8", newline="") as fh:
        fh.write(header + "window.ECO_WORLD = " + body + ";\n")

    rings = sum(len(v) for v in shapes.values())
    pts = sum(len(r) for v in shapes.values() for r in v)
    print(f"{len(shapes)} countries ({rings} rings, {pts} points), "
          f"{len(points)} point-only micro-states -> {os.path.getsize(OUT)/1024:.0f} KB")


if __name__ == "__main__":
    main()
